# Generated by Django 5.0.14 on 2025-05-30 00:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_dogparent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dogparent',
            name='birth_day',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения родителя'),
        ),
    ]
