# Generated by Django 5.0.14 on 2025-04-26 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dogs', '0003_alter_dog_birth_date_alter_dog_breed_alter_dog_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='breed',
            name='description',
            field=models.CharField(max_length=1000, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='breed',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Порода'),
        ),
    ]
